<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="EN911182" failures="1" tests="8" name="Demo Folder" time="92.726" errors="0" timestamp="2022-03-24T09:16:56 COT">
  <testcase classname="challenge.tests.Tests" name="addMovieToListAPIAndUI" time="10.261"/>
  <testcase classname="challenge.tests.Tests" name="failedLogin" time="1.28"/>
  <testcase classname="challenge.tests.Tests" name="intentionallyFailedLogin" time="1.702">
    <failure type="java.lang.AssertionError" message="expected [543n2FAIL!!!] but found [543n2]">
      <![CDATA[java.lang.AssertionError: expected [543n2FAIL!!!] but found [543n2]
at challenge.tests.Tests.intentionallyFailedLogin(Tests.java:243)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- intentionallyFailedLogin -->
  <testcase classname="challenge.tests.Tests" name="sortByDatesOnAscendingOrder" time="2.479"/>
  <testcase classname="challenge.tests.Tests" name="successfulLogin" time="2.069"/>
  <testcase classname="challenge.tests.Tests" name="successfulSearch" time="1.047"/>
  <testcase classname="challenge.tests.Tests" name="validateActingTimeline" time="3.447"/>
  <testcase classname="challenge.tests.Tests" name="verifyMovieGenreFilter" time="4.086"/>
</testsuite> <!-- Demo Folder -->
